---
# Variable "valeur" options:
# Disabled -> 0
# Enabled -> 1

  - name: Store Passwords Using Reversible Encryption (Disabled)
    win_security_policy:
      section: System Access
      key: ClearTextPassword
      value: 0
    register: result
    when: valeur == 'Disabled'

  - name: Store Passwords Using Reversible Encryption (Enabled)
    win_security_policy:
      section: System Access
      key: ClearTextPassword
      value: 1
    register: result
    when: define == 'Enabled'

# Store passwords using reversible encryption

# This security setting determines whether the operating system stores passwords using reversible encryption.

# This policy provides support for applications that use protocols that require knowledge of the user's password for authentication purposes.
# Storing passwords using reversible encryption is essentially the same as storing plaintext versions of the passwords.
# For this reason, this policy should never be enabled unless application requirements outweigh the need to protect password information.

# This policy is required when using Challenge-Handshake Authentication Protocol (CHAP) authentication through remote access or
# Internet Authentication Services (IAS). It is also required when using Digest Authentication in Internet Information Services (IIS).

# Default: Disabled.