---

# This will create a sheduled task.
# The task will run on the last saturday of each months.


          - name: Scheduled Task - Full Windows Defender Scan
            win_scheduled_task:
              name: WINDOWS_DEFENDER_FULL_SCAN_MONTHLY
              actions:
              - path: powershell.exe
                arguments: Start-MpScan -AsJob -ScanType FullScan
              triggers:
              - type: monthlydow
                months_of_year: ['January','February','March','April','May','June','July','August','September','October','November','December']
                days_of_week: 'saturday'
                weeks_of_month: 4
                start_boundary: '2023-07-29T11:00:00'
              username: System
              logon_type: password
              run_level: highest                                                                                                                                                                                                           