---
# Set "define" to any value between 1 and 999

  - name: Set Maximum Password Age
    win_security_policy:
      section: System Access
      key: MaximumPasswordAge
      value: "{{ valeur }}"
    register: result

# Maximum password age
# This security setting determines the period of time (in days) that a password can be used before the system requires the user to change it. 
# You can set passwords to expire after a number of days between 1 and 999, or you can specify that passwords never expire by setting the number of days to 0.
# If the maximum password age is between 1 and 999 days, the Minimum password age must be less than the maximum password age. 
# If the maximum password age is set to 0, the minimum password age can be any value between 0 and 998 days.

# Note: It is a security best practice to have passwords expire every 30 to 90 days, depending on your environment. 
# This way, an attacker has a limited amount of time in which to crack a user's password and have access to your network resources.

# Default: 42.