---
# Set "define" to any value between 1 and 998

  - name: Set Maximum Password Age
    win_security_policy:
      section: System Access
      key: MinimumPasswordAge
      value: "{{ valeur }}"
    register: result

# Minimum password age

#This security setting determines the period of time (in days) that a password must be used before the user can change it. 
# You can set a value between 1 and 998 days, or you can allow changes immediately by setting the number of days to 0.

# The minimum password age must be less than the Maximum password age, unless the maximum password age is set to 0,
# indicating that passwords will never expire. If the maximum password age is set to 0, the minimum password age can be set to any value between 0 and 998.

# Configure the minimum password age to be more than 0 if you want Enforce password history to be effective.
# Without a minimum password age, users can cycle through passwords repeatedly until they get to an old favorite.
# The default setting does not follow this recommendation, so that an administrator can specify a password for a user and then require
# the user to change the administrator-defined password when the user logs on. If the password history is set to 0,
# the user does not have to choose a new password. For this reason, Enforce password history is set to 1 by default.

# Default:

# 1 on domain controllers.
# 0 on stand-alone servers.

# Note: By default, member computers follow the configuration of their domain controllers.