---
  - name: Set Maximum Password Age
    win_security_policy:
      section: System Access
      key: MinimumPasswordLengthAudit
      value: "{{ valeur }}"
    register: result

# Minimum password length audit

# This security setting determines the minimum password length for which password length audit warning events are issued. 
# This setting may be configured from 1 to 128.

# You should only enable and configure this setting when trying to determine the potential impact of increasing the minimum password length
# setting in your environment.

# If this setting is not defined, audit events will not be issued.

# If this setting is defined and is less than or equal to the minimum password length setting, audit events will not be issued.

# If this setting is defined and is greater than the minimum password length setting, and the length of a new account password is less than this setting,
# an audit event will be issued.

# For more information see https://go.microsoft.com/fwlink/?LinkId=2097191.
