---

# This will create a scheduled task.
# The task will run on the last saturday of each months.
# The start time is triggered by the start_boundary time.
# The reccuring day is triggered by days_of_week.

          - hosts: test
            gather_facts: no
            tasks:
            - name: Scheduled Task - Full Windows Defender Scan - Powershell
              win_scheduled_task:
                name: WINDOWS_DEFENDER_FULL_SCAN_MONTHLY
                actions:
                - path: powershell.exe
                  arguments: Start-MpScan -AsJob -ScanType FullScan
                triggers:
                - type: monthlydow
                  months_of_year: ['January','February','March','April','May','June','July','August','September','October','November','December']
                  days_of_week: 'saturday'
                  weeks_of_month: 4
                  start_boundary: '2023-07-29T11:00:00'
                  #start_boundary: '{ansible_date_time_iso8601}'
                username: System
                logon_type: password 
                run_level: highest
